version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: koperasi_v3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d koperasi_v3"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/koperasi_v3?schema=public
      - JWT_SECRET=secret_key_koperasi_bakamla_v2
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data:
