version: '3.8'

services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Port 8080 di laptop/server akan diteruskan ke Port 80 di dalam container
      - "8080:80"
    restart: unless-stopped
    container_name: koperasi-landing-page
